In [1]:
import pandas as pd

In [2]:
hakaton_nn_1month = pd.read_excel('data/hakaton_nn_1month.xlsx')

In [3]:
data = pd.DataFrame(hakaton_nn_1month)

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
data.head()

party_rk               region              offenceshortstatement  \
0   622025641               Москва                Движение по обочине   
1   696133759  Воронежская область  Превышение скорости на 40-60 км/ч   
2  1057242004          Севастополь  Превышение скорости на 20-40 км/ч   
3   300624658      Республика Тыва  Превышение скорости на 20-40 км/ч   
4   702484296  Воронежская область  Превышение скорости на 20-40 км/ч   

  offencedate offencetime engine_type engine_power             body_type  \
0  2024-05-15    09:52:48        1.8        152.00     Универсал (5 дв.)   
1  2024-05-13    17:54:58        1.6         73.00         Седан (4 дв.)   
2  2024-05-10    00:29:11        2.5        145.00  Микроавтобус (5 дв.)   
3  2024-05-02    21:44:46        2.0        150.00         Седан (4 дв.)   
4  2024-04-28    16:25:51        2.3        155.00     Универсал (5 дв.)   

    auto_mark  auto_year    auto_model    color       gear_type car_price  \
0       SKODA     2011.0       OCTAVIA   ЧЕРНЫЙ  Автоматическая       712   
1  LADA (ВАЗ)     2011.0          2107    БЕЛЫЙ    Механическая       162   
2     HYUNDAI     2018.0  GRAND STAREX    СЕРЫЙ  Автоматическая      2601   
3  MITSUBISHI     2007.0        LANCER   ЧЕРНЫЙ    Механическая       410   
4        FORD     2004.0        ESCAPE  КРАСНЫЙ  Автоматическая       617   

  gender_cd   age marital_status_cd  children_cnt education_level_cd  \
0         M  23.0               UNM           0.0                UGR   
1         M  19.0               NaN           0.0                NaN   
2         M  43.0               NaN           NaN                NaN   
3         M  27.0               UNM           0.0                SCH   
4         F  42.0               MAR           0.0                GRD   

   person_monthly_income_amt  day_of_week public_holiday  
0                       80.0        Среда              f  
1                       45.0  Понедельник              f  
2                      500.0      Пятница              t  
3                       35.0      Четверг              f  
4                       50.0  Воскресенье              t

In [6]:
data['offencedatetime'] = pd.to_datetime(data['offencedate'].astype(str) + ' ' + data['offencetime'].astype(str), utc=False)

In [7]:
data.drop(columns=['offencedate', 'offencetime'], axis=1, inplace=True)

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97307 entries, 0 to 97306
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype         
---  ------                     --------------  -----         
 0   party_rk                   97307 non-null  int64         
 1   region                     97307 non-null  object        
 2   offenceshortstatement      97307 non-null  object        
 3   engine_type                97307 non-null  object        
 4   engine_power               97302 non-null  object        
 5   body_type                  97307 non-null  object        
 6   auto_mark                  97307 non-null  object        
 7   auto_year                  97306 non-null  float64       
 8   auto_model                 97307 non-null  object        
 9   color                      97307 non-null  object        
 10  gear_type                  97307 non-null  object        
 11  car_price                  90869 non-null  object        
 12  gend

In [9]:
data.describe()

party_rk     auto_year           age  children_cnt  \
count  9.730700e+04  97306.000000  97298.000000  85578.000000   
mean   5.449173e+08   2013.258545     37.610177      0.158861   
min    1.180000e+02   1910.000000      4.000000      0.000000   
25%    2.724617e+08   2009.000000     30.000000      0.000000   
50%    5.453081e+08   2013.000000     37.000000      0.000000   
75%    7.856263e+08   2018.000000     44.000000      0.000000   
max    1.228628e+09   2024.000000     88.000000      9.000000   
std    3.076227e+08      6.135811     10.598194      0.532164   

       person_monthly_income_amt                offencedatetime  
count               8.383200e+04                          97307  
mean                1.054343e+04  2024-05-15 22:00:42.481178368  
min                 0.000000e+00            2024-04-28 00:01:34  
25%                 7.000000e+01            2024-05-08 15:50:05  
50%                 1.150000e+02            2024-05-16 18:32:24  
75%                 2.000000e+02     2024-05-23 08:05:01.500000  
max                 8.691286e+08            2024-05-27 23:59:59  
std                 3.001781e+06                            NaN

Первым делом преобразовываем числовые переменные, а потом уже строковые

In [10]:
data['engine_type'] = data['engine_type'].where(pd.to_numeric(data['engine_type'], errors='coerce').notnull(), None)

In [11]:
data.engine_type = data.engine_type.astype(float)

In [12]:
data.engine_type.fillna(data.engine_type.median(), inplace=True)

/tmp/ipykernel_2190/2457929955.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.engine_type.fillna(data.engine_type.median(), inplace=True)


In [13]:
data['engine_power'] = data['engine_power'].where(pd.to_numeric(data['engine_power'], errors='coerce').notnull(), None)

In [14]:
data.engine_power = data.engine_power.astype(float)

In [15]:
data.engine_power.apply(lambda x: isinstance(x, float) and x.is_integer()).unique()

array([ True, False])

In [16]:
data.engine_power.fillna(data.engine_power.median(), inplace=True)

/tmp/ipykernel_2190/3920612850.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.engine_power.fillna(data.engine_power.median(), inplace=True)


In [17]:
data.engine_power.isnull().sum()

np.int64(0)

In [18]:
data.auto_year.unique()

array([2011., 2018., 2007., 2004., 2019., 2013., 2016., 2003., 2021.,
       2008., 2012., 2010., 2015., 2022., 2020., 2017., 2024., 2014.,
       2005., 2006., 1987., 2009., 2023., 2000., 2002., 1999., 1996.,
       1998., 2001., 1997., 1988., 1983., 1992., 1993., 1990., 1995.,
       1986., 1991., 1994., 1985., 1989., 1984.,   nan, 1982., 1980.,
       1910., 1981.])

In [19]:
data.auto_year.isnull().sum()

np.int64(1)

In [20]:
from sklearn.impute import KNNImputer

In [21]:
imputer = KNNImputer(n_neighbors=2)
data['auto_year'] = imputer.fit_transform(data[['auto_year']])

In [22]:
data.auto_year.unique()

array([2011.        , 2018.        , 2007.        , 2004.        ,
       2019.        , 2013.        , 2016.        , 2003.        ,
       2021.        , 2008.        , 2012.        , 2010.        ,
       2015.        , 2022.        , 2020.        , 2017.        ,
       2024.        , 2014.        , 2005.        , 2006.        ,
       1987.        , 2009.        , 2023.        , 2000.        ,
       2002.        , 1999.        , 1996.        , 1998.        ,
       2001.        , 1997.        , 1988.        , 1983.        ,
       1992.        , 1993.        , 1990.        , 1995.        ,
       1986.        , 1991.        , 1994.        , 1985.        ,
       1989.        , 1984.        , 2013.25854521, 1982.        ,
       1980.        , 1910.        , 1981.        ])

In [23]:
data.auto_year = data.auto_year.astype(int)

In [24]:
data.auto_year.unique()

array([2011, 2018, 2007, 2004, 2019, 2013, 2016, 2003, 2021, 2008, 2012,
       2010, 2015, 2022, 2020, 2017, 2024, 2014, 2005, 2006, 1987, 2009,
       2023, 2000, 2002, 1999, 1996, 1998, 2001, 1997, 1988, 1983, 1992,
       1993, 1990, 1995, 1986, 1991, 1994, 1985, 1989, 1984, 1982, 1980,
       1910, 1981])

In [25]:
data['car_price'] = pd.to_numeric(data['car_price'], errors='coerce')

In [26]:
data.car_price.isnull().sum()

np.int64(6439)

In [27]:
data.car_price.fillna(data.car_price.median(), inplace=True)

/tmp/ipykernel_2190/374695332.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.car_price.fillna(data.car_price.median(), inplace=True)


In [28]:
data.car_price = data.car_price.astype(int)

In [29]:
data.age.isnull().sum()

np.int64(9)

In [30]:
data.age.fillna(data.age.median(), inplace=True)

/tmp/ipykernel_2190/1727531274.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.age.fillna(data.age.median(), inplace=True)


In [31]:
data.age = data.age.astype(int)

In [32]:
data.children_cnt.unique()

array([ 0., nan,  1.,  2.,  3.,  5.,  4.,  6.,  7.,  8.,  9.])

In [33]:
data.children_cnt = imputer.fit_transform(data[['children_cnt']])

In [34]:
data.children_cnt = data.children_cnt.astype(int)

In [35]:
data.person_monthly_income_amt.isnull().sum()

np.int64(13475)

In [36]:
data.person_monthly_income_amt.fillna(data.person_monthly_income_amt.mean(), inplace=True)

/tmp/ipykernel_2190/3087565678.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.person_monthly_income_amt.fillna(data.person_monthly_income_amt.mean(), inplace=True)


Теперь приступаем к текстовым и бинарным форматам

In [37]:
data.gender_cd.unique()

array(['M', 'F', nan, '32'], dtype=object)

In [38]:
import numpy as np

In [39]:
data[data['gender_cd']=='32'] = np.nan

In [40]:
data.gender_cd.unique()

array(['M', 'F', nan], dtype=object)

In [41]:
data['gender_cd'] = data['gender_cd'].replace('M', 1)
data['gender_cd'] = data['gender_cd'].replace('F', 0)
#M=1, F=0

/tmp/ipykernel_2190/134446724.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['gender_cd'] = data['gender_cd'].replace('F', 0)


In [42]:
data.gender_cd.fillna(data.gender_cd.mean(), inplace=True)

/tmp/ipykernel_2190/783131180.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.gender_cd.fillna(data.gender_cd.mean(), inplace=True)


In [43]:
data.gender_cd = data.gender_cd.astype(int)

In [44]:
data.public_holiday.unique()

array(['f', 't', nan], dtype=object)

In [45]:
data.public_holiday.replace('f', 1, inplace=True)
data.public_holiday.replace('t', 0, inplace=True)
#f=1, t=0

/tmp/ipykernel_2190/3145013189.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.public_holiday.replace('f', 1, inplace=True)
/tmp/ipykernel_2190/3145013189.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try

In [46]:
data.public_holiday.fillna(data.public_holiday.mean(), inplace=True)

In [47]:
data.public_holiday = data.public_holiday.astype(int)

In [48]:
data.rename(columns={'public_holiday': 'public_holiday_1-f_0-t', 'gender_cd': 'gender_cd_M-1_F-0'}, inplace=True)

In [49]:
data.head()

party_rk               region              offenceshortstatement  \
0  6.220256e+08               Москва                Движение по обочине   
1  6.961338e+08  Воронежская область  Превышение скорости на 40-60 км/ч   
2  1.057242e+09          Севастополь  Превышение скорости на 20-40 км/ч   
3  3.006247e+08      Республика Тыва  Превышение скорости на 20-40 км/ч   
4  7.024843e+08  Воронежская область  Превышение скорости на 20-40 км/ч   

   engine_type  engine_power             body_type   auto_mark  auto_year  \
0          1.8         152.0     Универсал (5 дв.)       SKODA     2011.0   
1          1.6          73.0         Седан (4 дв.)  LADA (ВАЗ)     2011.0   
2          2.5         145.0  Микроавтобус (5 дв.)     HYUNDAI     2018.0   
3          2.0         150.0         Седан (4 дв.)  MITSUBISHI     2007.0   
4          2.3         155.0     Универсал (5 дв.)        FORD     2004.0   

     auto_model    color       gear_type  car_price  gender_cd_M-1_F-0   age  \
0       OCTAVIA   ЧЕРНЫЙ  Автоматическая      712.0                  1  23.0   
1          2107    БЕЛЫЙ    Механическая      162.0                  1  19.0   
2  GRAND STAREX    СЕРЫЙ  Автоматическая     2601.0                  1  43.0   
3        LANCER   ЧЕРНЫЙ    Механическая      410.0                  1  27.0   
4        ESCAPE  КРАСНЫЙ  Автоматическая      617.0                  0  42.0   

  marital_status_cd  children_cnt education_level_cd  \
0               UNM           0.0                UGR   
1               NaN           0.0                NaN   
2               NaN           0.0                NaN   
3               UNM           0.0                SCH   
4               MAR           0.0                GRD   

   person_monthly_income_amt  day_of_week  public_holiday_1-f_0-t  \
0                       80.0        Среда                       1   
1                       45.0  Понедельник                       1   
2                      500.0      Пятница                       0   
3                       35.0      Четверг                       1   
4                       50.0  Воскресенье                       0   

      offencedatetime  
0 2024-05-15 09:52:48  
1 2024-05-13 17:54:58  
2 2024-05-10 00:29:11  
3 2024-05-02 21:44:46  
4 2024-04-28 16:25:51

In [50]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97307 entries, 0 to 97306
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype         
---  ------                     --------------  -----         
 0   party_rk                   97306 non-null  float64       
 1   region                     97306 non-null  object        
 2   offenceshortstatement      97306 non-null  object        
 3   engine_type                97306 non-null  float64       
 4   engine_power               97306 non-null  float64       
 5   body_type                  97306 non-null  object        
 6   auto_mark                  97306 non-null  object        
 7   auto_year                  97306 non-null  float64       
 8   auto_model                 97306 non-null  object        
 9   color                      97306 non-null  object        
 10  gear_type                  97306 non-null  object        
 11  car_price                  97306 non-null  float64       
 12  gend

In [51]:
data.describe()

party_rk   engine_type  engine_power     auto_year     car_price  \
count  9.730600e+04  97306.000000  97306.000000  97306.000000  97306.000000   
mean   5.449193e+08      2.156845    161.532329   2013.258463   1581.552391   
min    1.180000e+02      0.000000      0.000000   1910.000000     46.000000   
25%    2.724549e+08      1.600000    107.000000   2009.000000    659.000000   
50%    5.453083e+08      1.800000    145.000000   2013.000000   1105.000000   
75%    7.856307e+08      2.400000    190.000000   2018.000000   1945.000000   
max    1.228628e+09    999.000000   1770.000000   2024.000000  35470.000000   
std    3.076237e+08      8.494550     79.588675      6.135761   1622.693079   

       gender_cd_M-1_F-0           age  children_cnt  \
count       97307.000000  97306.000000  97306.000000   
mean            0.687299     37.610127      0.139714   
min             0.000000      4.000000      0.000000   
25%             0.000000     30.000000      0.000000   
50%             1.000000     37.000000      0.000000   
75%             1.000000     44.000000      0.000000   
max             1.000000     88.000000      9.000000   
std             0.463596     10.597759      0.501737   

       person_monthly_income_amt  public_holiday_1-f_0-t  \
count               9.730600e+04            97307.000000   
mean                1.054343e+04                0.748980   
min                 0.000000e+00                0.000000   
25%                 8.000000e+01                0.000000   
50%                 1.400000e+02                1.000000   
75%                 3.000000e+02                1.000000   
max                 8.691286e+08                1.000000   
std                 2.786210e+06                0.433602   

                     offencedatetime  
count                          97306  
mean   2024-05-15 22:00:41.765831680  
min              2024-04-28 00:01:34  
25%              2024-05-08 15:49:59  
50%              2024-05-16 18:32:26  
75%    2024-05-23 08:05:02.750000128  
max              2024-05-27 23:59:59  
std                              NaN

In [52]:
data.to_csv('data/data.csv')